name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Clean install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

    # Tạm thời comment out tests và linting
    # - name: Run tests
    #   run: npm test

    # - name: Run linting
    #   run: npm run lint
